[package]
name = "sshpass-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expectrl = "0.6.0"
console = "0.15.1"
clap = { version = "4.0.4", features = ["derive"] }
anyhow = "*"